version: '3.4'

services:
  dealnotifier.api:
    image: ${DOCKER_REGISTRY-}dealnotifierapi
    build:
      context: .
      dockerfile: DealNotifier.API/Dockerfile

  ebaydatasyncworker:
    image: ${DOCKER_REGISTRY-}dealnotifierinfrastructureebaydatasyncworker
    build:
      context: .
      dockerfile: DealNotifier.Infrastructure.EbayDataSyncWorker/Dockerfile


  samkeydatasyncworker:
    image: ${DOCKER_REGISTRY-}dealnotifierinfrastructuresamkeydatasyncworker
    build:
      context: .
      dockerfile: DealNotifier.Infrastructure.SamkeyDataSyncWorker/Dockerfile


  t-unlockdatasyncworker:
    image: ${DOCKER_REGISTRY-}dealnotifierinfrastructuretunlockdatasyncworker
    build:
      context: .
      dockerfile: DealNotifier.Infrastructure.T-UnlockDataSyncWorker/Dockerfile
  
  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrations

  add-stored-procedures:
    image: mcr.microsoft.com/mssql-tools