version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - ACCEPT_EULA=Y
    ports:
      - "1434:1433"
    volumes:
      - dbdata:/var/opt/mssql
    

  migrate:
    build:
        context: ./
        dockerfile: Dockerfile.migrations
    environment:
         - ConnectionStrings__DealNotifierConnection=${CONNECTION_STRING}
    volumes:
      - ./wait-for-it.sh:/app/wait-for-it.sh
    entrypoint: ["/bin/sh", "-c", "/app/wait-for-it.sh db:1433 -- dotnet ef database update --startup-project ./WebApi/WebApi.csproj --context applicationDbContext"]
    depends_on:
        - db

  add-stored-procedures:
    image: mcr.microsoft.com/mssql-tools
    environment:
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - ACCEPT_EULA=Y
    volumes:
      - ./StoredProcedures.sql:/tmp/StoredProcedures.sql
      - ./wait-for-it.sh:/app/wait-for-it.sh
    depends_on:
      - db
      - migrate
    entrypoint: ["/bin/sh", "-c", "/app/wait-for-it.sh db:1433 -- /opt/mssql-tools/bin/sqlcmd -S db -U SA -P $$MSSQL_SA_PASSWORD -i /tmp/StoredProcedures.sql"]
    

  web-api:
    image: web-api:1.0
    build: 
        context: ./
        dockerfile: WebApi/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DealNotifierConnection=${CONNECTION_STRING}
    depends_on:
    - db
    - migrate
    - add-stored-procedures
    volumes:
          - ./wait-for-it.sh:/app/wait-for-it.sh
    entrypoint: ["/bin/sh", "-c", "/app/wait-for-it.sh db:1433 -- dotnet /app/WebApi.dll"]
  ebay-data-sync-worker:
    image: ebay-data-sync-worker:1.0
    build: 
        context: ./
        dockerfile: EbayDataSyncWorker/Dockerfile
    environment:
        - ConnectionStrings__DealNotifierConnection=${CONNECTION_STRING}
        - ClientId=${CLIENT_ID}
        - ClientSecret=${CLIENT_SECRET}
        - RefreshToken=${REFRESH_TOKEN}
    depends_on:
        - db
    volumes:
      - ./wait-for-it.sh:/app/wait-for-it.sh
    entrypoint: ["/bin/sh", "-c", "/app/wait-for-it.sh db:1433 -- dotnet /app/EbayDataSyncWorker.dll"]
  t-unlock-data-sync-worker:
    image: t-unlock-data-sync-worker:1.0
    build: 
        context: ./
        dockerfile: T-UnlockDataSyncWorker/Dockerfile
    environment:
        - ConnectionStrings__DealNotifierConnection=${CONNECTION_STRING}
    depends_on:
    - db


volumes:
  dbdata: