//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_User
    {
        public int Id { get; set; }
        public string NAME { get; set; }
        public string USER_NAME { get; set; }
        public string PASSWORD { get; set; }
    }
}
