//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WebScrapingEntities : DbContext
    {
        public WebScrapingEntities()
            : base("name=WebScrapingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_User> C_User { get; set; }
        public virtual DbSet<BlackList> BlackLists { get; set; }
        public virtual DbSet<Condition> Conditions { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Shop> Shops { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Supported> Supporteds { get; set; }
        public virtual DbSet<Type> Types { get; set; }
    
        public virtual int Filter(string data, string order, string min, string max, string types, string shops, string condition)
        {
            var dataParameter = data != null ?
                new ObjectParameter("Data", data) :
                new ObjectParameter("Data", typeof(string));
    
            var orderParameter = order != null ?
                new ObjectParameter("Order", order) :
                new ObjectParameter("Order", typeof(string));
    
            var minParameter = min != null ?
                new ObjectParameter("Min", min) :
                new ObjectParameter("Min", typeof(string));
    
            var maxParameter = max != null ?
                new ObjectParameter("Max", max) :
                new ObjectParameter("Max", typeof(string));
    
            var typesParameter = types != null ?
                new ObjectParameter("Types", types) :
                new ObjectParameter("Types", typeof(string));
    
            var shopsParameter = shops != null ?
                new ObjectParameter("Shops", shops) :
                new ObjectParameter("Shops", typeof(string));
    
            var conditionParameter = condition != null ?
                new ObjectParameter("Condition", condition) :
                new ObjectParameter("Condition", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Filter", dataParameter, orderParameter, minParameter, maxParameter, typesParameter, shopsParameter, conditionParameter);
        }
    
        public virtual ObjectResult<Offer_Result> Offer(string tYPE)
        {
            var tYPEParameter = tYPE != null ?
                new ObjectParameter("TYPE", tYPE) :
                new ObjectParameter("TYPE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Offer_Result>("Offer", tYPEParameter);
        }
    
        public virtual int SP_ADD(string nAME, Nullable<decimal> pRICE, string lINK, Nullable<int> cONDITION, Nullable<int> sHOP, string iMAGE, Nullable<int> tYPE)
        {
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(string));
    
            var pRICEParameter = pRICE.HasValue ?
                new ObjectParameter("PRICE", pRICE) :
                new ObjectParameter("PRICE", typeof(decimal));
    
            var lINKParameter = lINK != null ?
                new ObjectParameter("LINK", lINK) :
                new ObjectParameter("LINK", typeof(string));
    
            var cONDITIONParameter = cONDITION.HasValue ?
                new ObjectParameter("CONDITION", cONDITION) :
                new ObjectParameter("CONDITION", typeof(int));
    
            var sHOPParameter = sHOP.HasValue ?
                new ObjectParameter("SHOP", sHOP) :
                new ObjectParameter("SHOP", typeof(int));
    
            var iMAGEParameter = iMAGE != null ?
                new ObjectParameter("IMAGE", iMAGE) :
                new ObjectParameter("IMAGE", typeof(string));
    
            var tYPEParameter = tYPE.HasValue ?
                new ObjectParameter("TYPE", tYPE) :
                new ObjectParameter("TYPE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ADD", nAMEParameter, pRICEParameter, lINKParameter, cONDITIONParameter, sHOPParameter, iMAGEParameter, tYPEParameter);
        }
    
        public virtual int SP_DELETE(string iDS)
        {
            var iDSParameter = iDS != null ?
                new ObjectParameter("IDS", iDS) :
                new ObjectParameter("IDS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE", iDSParameter);
        }
    
        public virtual ObjectResult<string> SP_GET_BLACK_LIST()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_GET_BLACK_LIST");
        }
    
        public virtual ObjectResult<SP_GET_ONE_Result> SP_GET_ONE(string iD)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_ONE_Result>("SP_GET_ONE", iDParameter);
        }
    
        public virtual ObjectResult<SP_GetAllLinks_Result> SP_GetAllLinks()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetAllLinks_Result>("SP_GetAllLinks");
        }
    
        public virtual int SP_UPDATE_PRICE(Nullable<int> iD, Nullable<decimal> pRICE, Nullable<decimal> oLD_PRICE, Nullable<decimal> sAVNG, Nullable<decimal> sAVNG_PERCENT, string nAME, string iMAGE)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var pRICEParameter = pRICE.HasValue ?
                new ObjectParameter("PRICE", pRICE) :
                new ObjectParameter("PRICE", typeof(decimal));
    
            var oLD_PRICEParameter = oLD_PRICE.HasValue ?
                new ObjectParameter("OLD_PRICE", oLD_PRICE) :
                new ObjectParameter("OLD_PRICE", typeof(decimal));
    
            var sAVNGParameter = sAVNG.HasValue ?
                new ObjectParameter("SAVNG", sAVNG) :
                new ObjectParameter("SAVNG", typeof(decimal));
    
            var sAVNG_PERCENTParameter = sAVNG_PERCENT.HasValue ?
                new ObjectParameter("SAVNG_PERCENT", sAVNG_PERCENT) :
                new ObjectParameter("SAVNG_PERCENT", typeof(decimal));
    
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(string));
    
            var iMAGEParameter = iMAGE != null ?
                new ObjectParameter("IMAGE", iMAGE) :
                new ObjectParameter("IMAGE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_PRICE", iDParameter, pRICEParameter, oLD_PRICEParameter, sAVNGParameter, sAVNG_PERCENTParameter, nAMEParameter, iMAGEParameter);
        }
    
        public virtual int SP_UPDATE_STATUS(Nullable<int> iD, Nullable<int> sTATUS)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var sTATUSParameter = sTATUS.HasValue ?
                new ObjectParameter("STATUS", sTATUS) :
                new ObjectParameter("STATUS", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_STATUS", iDParameter, sTATUSParameter);
        }
    }
}
