//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supported
    {
        public int ID { get; set; }
        public string NUMBER_MODEL { get; set; }
        public string NAME_MODEL { get; set; }
        public string TOOL { get; set; }
        public string SUPPORT_VERSION { get; set; }
        public string SUPPORT_BIT { get; set; }
        public string CARRIERS { get; set; }
        public string COMMENT { get; set; }
    }
}
