//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supported
    {
        public int ID { get; set; }
        public string NUMBER_MODEL { get; set; }
        public string NAME_MODEL { get; set; }
        public string TOOL { get; set; }
        public string SUPPORT_VERSION { get; set; }
        public string SUPPORT_BIT { get; set; }
        public string CARRIERS { get; set; }
        public string COMMENT { get; set; }
    }
}
